-- MySQL Script generated by MySQL Workbench
-- 2018年06月06日 星期三 23时11分07秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_user_principal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user_principal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user_principal` (
  `id` BIGINT NOT NULL,
  `username` VARCHAR(45) NULL,
  `credential` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user_profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user_profile` (
  `id` BIGINT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `principal_id` BIGINT NOT NULL,
  `sex` TINYINT NOT NULL,
  `credit` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_profile_t_user_principal1_idx` (`principal_id` ASC),
  CONSTRAINT `fk_t_user_profile_t_user_principal1`
    FOREIGN KEY (`principal_id`)
    REFERENCES `mydb`.`t_user_principal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_post` (
  `id` BIGINT NOT NULL,
  `content` VARCHAR(255) NULL,
  `arthor_id` BIGINT NOT NULL,
  `arthor_username` VARCHAR(45) NOT NULL,
  `post_time` DATETIME NOT NULL,
  `last_modified_time` DATETIME NULL,
  `reply_post_id` BIGINT NULL,
  `topic_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_post_t_topic1_idx` (`topic_id` ASC),
  INDEX `fk_t_post_t_user_profile1_idx` (`arthor_id` ASC),
  CONSTRAINT `fk_t_post_t_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `mydb`.`t_topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_post_t_user_profile1`
    FOREIGN KEY (`arthor_id`)
    REFERENCES `mydb`.`t_user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_topic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_topic` (
  `id` BIGINT NOT NULL,
  `arthor_username` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `post_time` DATETIME NOT NULL,
  `last_reply_time` DATETIME NOT NULL,
  `last_reply_username` VARCHAR(45) NOT NULL,
  `last_reply_uid` BIGINT NOT NULL,
  `views` INT NULL,
  `replies` INT NULL,
  `main_post_id` BIGINT NULL,
  `arthor_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_topic_t_post_idx` (`main_post_id` ASC),
  INDEX `fk_t_topic_t_user_profile1_idx` (`arthor_id` ASC),
  CONSTRAINT `fk_t_topic_t_post`
    FOREIGN KEY (`main_post_id`)
    REFERENCES `mydb`.`t_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_topic_t_user_profile1`
    FOREIGN KEY (`arthor_id`)
    REFERENCES `mydb`.`t_user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_subscription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_subscription` (
  `id` BIGINT NOT NULL,
  `lastReadTime` DATETIME NOT NULL,
  `userId` BIGINT NOT NULL,
  `subscription_type` TINYINT NOT NULL,
  `topic_id` BIGINT NOT NULL,
  `post_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_subscription_t_topic1_idx` (`topic_id` ASC),
  INDEX `fk_t_subscription_t_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_t_subscription_t_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `mydb`.`t_topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_subscription_t_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`t_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_subscription_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_subscription_config` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_subscription_config` (
  `id` BIGINT NOT NULL,
  `like_topic` TINYINT NULL DEFAULT 1,
  `like_post` TINYINT NULL DEFAULT 1,
  `pub_topic` TINYINT NULL DEFAULT 1,
  `pub_post` TINYINT NULL DEFAULT 1,
  `t_user_profile_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_subscription_config_t_user_profile1_idx` (`t_user_profile_id` ASC),
  CONSTRAINT `fk_t_subscription_config_t_user_profile1`
    FOREIGN KEY (`t_user_profile_id`)
    REFERENCES `mydb`.`t_user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
