-- MySQL Script generated by MySQL Workbench
-- 2018年06月15日 星期五 00时29分53秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema verrickt_security
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema verrickt_security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `verrickt_security` DEFAULT CHARACTER SET utf8 ;
USE `verrickt_security` ;

-- -----------------------------------------------------
-- Table `verrickt_security`.`t_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verrickt_security`.`t_permission` ;

CREATE TABLE IF NOT EXISTS `verrickt_security`.`t_permission` (
  `id` INT NOT NULL,
  `perm_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verrickt_security`.`t_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verrickt_security`.`t_role` ;

CREATE TABLE IF NOT EXISTS `verrickt_security`.`t_role` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verrickt_security`.`t_user_principal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verrickt_security`.`t_user_principal` ;

CREATE TABLE IF NOT EXISTS `verrickt_security`.`t_user_principal` (
  `id` BIGINT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_lock` TINYINT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verrickt_security`.`t_role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verrickt_security`.`t_role_permission` ;

CREATE TABLE IF NOT EXISTS `verrickt_security`.`t_role_permission` (
  `id` INT NOT NULL,
  `t_role_id` INT NOT NULL,
  `t_permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_role_permission_t_role_idx` (`t_role_id` ASC),
  INDEX `fk_t_role_permission_t_permission1_idx` (`t_permission_id` ASC),
  CONSTRAINT `fk_t_role_permission_t_role`
    FOREIGN KEY (`t_role_id`)
    REFERENCES `verrickt_security`.`t_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_role_permission_t_permission1`
    FOREIGN KEY (`t_permission_id`)
    REFERENCES `verrickt_security`.`t_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verrickt_security`.`t_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verrickt_security`.`t_user_role` ;

CREATE TABLE IF NOT EXISTS `verrickt_security`.`t_user_role` (
  `id` BIGINT NOT NULL,
  `t_role_id` INT NOT NULL,
  `t_user_principal_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_role_t_role1_idx` (`t_role_id` ASC),
  INDEX `fk_t_user_role_t_user_principal1_idx` (`t_user_principal_id` ASC),
  CONSTRAINT `fk_t_user_role_t_role1`
    FOREIGN KEY (`t_role_id`)
    REFERENCES `verrickt_security`.`t_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_role_t_user_principal1`
    FOREIGN KEY (`t_user_principal_id`)
    REFERENCES `verrickt_security`.`t_user_principal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
